name: ci

on:
  push:
    branches:  [main, master]
  pull_request:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install node packages
        run: npm ci
        shell: bash
      - name: Build
        run: npm run build
        shell: bash